---
- name: installing remi repository
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Disable selinux
  selinux:
      state: disabled  

- name: enable latest php version and install php
  yum:
    enablerepo: "remi,remi-php72"
    name: php
    state: latest

- name: Install dependencies
  yum:
    enablerepo: "remi,remi-php72"
    name: "{{ item }}"
    state: present
  loop: ['yum-utils', 'php', 'php-mcrypt', 'php-cli', 'php-gd', 'php-curl', 'php-mysql', 'php-ldap', 'php-zip', 'php-fileinfo', 'httpd']
  
- name: Enable and start apache at boot time
  systemd:
    enabled: yes
    state: started
    name: httpd

- name: Untar wordpress application
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html/
    extra_opts: [--strip-components=1]
    owner: apache
    group: apache
    remote_src: yes
  notify: apache restart    

- name: configuring wp-config.php file
  template:
    src: wp-config.php
    dest: /var/www/html/
    owner: apache
    group: apache
  notify: apache restart

