---
- name: Install the latest version of mariadb
  yum: name="{{item}}" state=present
  loop:
    - MySQL-python
    - mariadb-server

- name: enable mariadb service
  systemd:
    enabled: yes
    name: mariadb

- name: start mariadb service
  systemd:
    name: mariadb
    state: started

- name: create admin user with password
  mysql_user:
    name: "{{db_user}}"
    host: '%'
    password: "{{db_pass}}"
    priv: '*.*:ALL'
    state: present

- name: create database 
  mysql_db:
    name: "{{db_name}}"
    state: present
