---
- name: Installing database
  hosts: dbservers
  vars_files:
          - ./vars/main.yaml
          - ./vars/common.yaml
  roles:
    - db  

- name: Installing wordpress
  hosts: appservers
  vars_files:
          - ./vars/main.yaml
          - ./vars/common.yaml

  roles:
    - app

